/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e9e8e6",
        "inverse-surface": "#2f3130",
        "tertiary": "#000000",
        "surface-tint": "#615e5c",
        "tertiary-container": "#291800",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#faf9f7",
        "on-tertiary-fixed-variant": "#5e4114",
        "on-secondary-fixed": "#291800",
        "primary-fixed-dim": "#cbc5c3",
        "surface-container-highest": "#e3e2e0",
        "surface-container-low": "#f4f3f1",
        "on-primary-fixed": "#1d1b1a",
        "surface": "#faf9f7",
        "primary": "#181615",
        "on-secondary-container": "#785a2b",
        "on-surface": "#1a1c1b",
        "background": "#faf9f7",
        "inverse-primary": "#cbc5c3",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fdd39a",
        "on-surface-variant": "#4d4541",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#e8c088",
        "secondary-fixed": "#ffddb1",
        "on-primary-fixed-variant": "#494645",
        "on-tertiary-container": "#a17e4b",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#e9c086",
        "tertiary-fixed": "#ffddb1",
        "outline": "#7f7570",
        "surface-variant": "#e3e2e0",
        "primary-container": "#1d1b1a",
        "outline-variant": "#d0c4be",
        "surface-container": "#efeeec",
        "surface-dim": "#dadad8",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#5d4215",
        "on-primary-container": "#878381",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#291800",
        "on-background": "#1a1c1b",
        "primary-fixed": "#e7e1df",
        "secondary": "#C09B66",
        "secondary-dark": "#77592a",
        "inverse-on-surface": "#f1f1ef",
        "stone-border": "#E6E0D6"
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "4rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "margin": "1.25rem",
        "gutter-desktop": "2.5rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-xl": "3rem"
      },
      fontFamily: {
        sans: ["'IBM Plex Sans Arabic'", "'IBM Plex Sans'", "sans-serif"],
        body: ["'IBM Plex Sans Arabic'", "'IBM Plex Sans'", "sans-serif"],
        heading: ["'IBM Plex Sans Arabic'", "'IBM Plex Sans'", "sans-serif"]
      }
    },
  },
  plugins: [],
}
